#!/bin/bash

query=$(printf '%s' "$*" | tr ' ' '+')

if [ -z $query ]; then exit 0; fi

mkdir -p "$HOME/.cache/yt"
curl -s "https://yewtu.be/search?q=%$query" > "$HOME/.cache/yt/temp.html"
cachedpage="cat $HOME/.cache/yt/temp.html"
vidlist=$( $cachedpage | grep -Eo "watch\?v=.{11}")

titlelist=''

for i in $vidlist
do
	title="["`$cachedpage | pup 'a[href="/'$i'"] + div p.channel-name text{}'`"] "`$cachedpage | pup 'a[href="/'$i'"] > p text{}'`"\t\t$i"
	if ! [[ $titlelist =~ $i ]]
	then 
		titlelist=$titlelist"\n"$title
	fi
done

vid=$(echo -e $titlelist | uniq | fzf | awk 'BEGIN { FS = "\t\t" } ; {print $2}')

if [ -z $vid ]; then exit 0; fi

url="https://youtube.com/$vid"
# program=$(printf "mpv\ntermux-open-url" | fzf)
program="termux-open-url"

rm "$HOME/.cache/yt/temp.html"
bash $program $url
